const projectData = [
    {
        title: "Financify",
        date: "08/21",
        description: "A web-app made using MERN stack which acts as a hub for all the transactions, subscriptions and goals a person wants to keep a track of. Record your transactions by just clicking a photo of the bill/receipt.",
        tagline: "A full stack MERN app",
        tags: ["MongoDB", "Express", "React", "Node.js"],
        liveLink: "https://financify-zeta.netlify.app/",
        githubLink: "https://github.com/Ishaan-10/FINANCIFY",
        image: "https://raw.githubusercontent.com/Ishaan-10/FINANCIFY/main/client/src/images/landing.png",
    },
    {
        title: "Yelp Camp",
        date: "04/21",
        description: "A Yelp like web app for campgrounds. View , create , review information on various campgrounds from around the world. Added Maps , Authorization , Image upload and many more features.",
        tagline: "A full stack web app",
        tags: ["MongoDB", "Express", "EJS", "Node.js"],
        liveLink: "",
        githubLink: "https://github.com/Ishaan-10/Yelp-Camp",
        image: "https://gcdn.pbrd.co/images/7DJD3J5eKZBb.png?o=1",
    },
    {
        title: "Github User Finder",
        date: "05/21",
        description: "A Web App to help you quickly search for GitHub users and view their stats and top repositories. Stats include top repos , followers , following , bio , image , etc",
        tagline: "Web App using React and GitHub API",
        tags: ["React","Github API"],
        liveLink: "https://findingithubusers.netlify.app/",
        githubLink: "https://github.com/Ishaan-10/github-finder",
        image: "https://raw.githubusercontent.com/Ishaan-10/github-finder/main/public/githubfinder.jpg",
    },
    {
        title: "Amazon Web Scraper",
        date: "07/21",
        description: "A command line tool to scrape for prices on amazon and mail the user when the price falls below a certain amount. Used Nightmare and Nodemailer npm packages.",
        tagline: "Web App using React and GitHub API",
        tags: ["Node.js"],
        liveLink: "",
        githubLink: "https://github.com/Ishaan-10/Web-Scraping",
        image: "https://gcdn.pbrd.co/images/sTzokthCQOzK.png?o=1",
    },
    {
        title: "Cook Book",
        date: "07/21",
        description: "A small project to store recipes of various food items. Used browser storage to save necessary data.",
        tagline: "Web App using React and browser storage to store recipes",
        tags: ["React"],
        liveLink: "https://reciepeswithreact.netlify.app/",
        githubLink: "https://github.com/Ishaan-10/CookingWithReact",
        image: "https://gcdn.pbrd.co/images/hGA8G4OCgQxQ.png?o=1",
    },

]

export default projectData;